[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "personal-parakeet"
version = "3.0.0"
description = "Real-time dictation with a transparent, floating UI."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "flet>=0.21.0",
    "sounddevice>=0.4.6",
    "numpy>=1.24.0",
    "torch>=2.0.0",
    "nemo-toolkit[asr]>=1.23.0",
    "keyboard>=0.13.5",
    "pyperclip>=1.8.2",
    "webrtcvad>=2.0.10",
    "scipy>=1.10.0",
    "librosa>=0.10.0",
]

[project.optional-dependencies]
windows = [
    "pywin32>=306",
]
linux = [
    "python-xlib>=0.33",
    "pynput>=1.7.6",
    "pyaudio>=0.2.13",
    "dbus-next>=0.2.3",
]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
    "pyinstaller>=5.0",
]

[project.scripts]
parakeet = "personalparakeet.v3.main:main"

[tool.setuptools.packages.find]
where = ["v3-flet"]
