[tool.poetry]
name = "personalparakeet"
version = "3.0.0"
description = "Real-time dictation system with transparent floating UI"
authors = ["PersonalParakeet Team"]
readme = "README.md"
packages = [{include = "personalparakeet", from = "src"}]
include = [
    "src/personalparakeet/models/*.onnx",
    "src/personalparakeet/models/*.pt",
    "src/personalparakeet/models/*.json",
    "src/personalparakeet/assets/**/*"
]

[tool.poetry.dependencies]
python = "^3.11"
flet = "^0.28.3"
sounddevice = "^0.4.6"
numpy = "^1.24.0"
scipy = "^1.10.0"
soundfile = "^0.12.0"
pyaudio = "^0.2.11"
python-dotenv = "^1.0.0"
dataclasses-json = "^0.6.0"
keyboard = "^0.13.5"
pynput = "^1.8.1"
pyperclip = "^1.9.0"
networkx = "^3.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.0.0"
black = "^23.0.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
mypy = "^1.0.0"
openai-whisper = "^20250625"

[tool.poetry.scripts]
personalparakeet = "personalparakeet.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
