# PersonalParakeet Test Configuration with Mock STT
audio:
  device_id: 7  # HyperX QuadCast
  sample_rate: 16000
  chunk_duration_ms: 30
  use_mock_stt: true  # Force mock STT for testing without NeMo

injection:
  strategy: "pyautogui"
  delay_ms: 0

clarity:
  enabled: true
  rules_enabled: true