name: personalparakeet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.11
  
  # PyTorch with CUDA support
  - pytorch=2.1.2
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  
  # CUDA libraries
  - cudatoolkit=12.1
  - cudnn=8.9.2
  
  # NeMo and dependencies
  - pip  # Need pip to install NeMo
  
  # Audio processing (conda versions for better CUDA compatibility)
  - numpy=1.26
  - scipy=1.11
  - librosa=0.10.1
  
  # Development tools
  - ipython
  - jupyter
  
  # Pip dependencies (for packages not in conda)
  - pip:
    # NeMo toolkit with ASR support
    - nemo-toolkit[asr]==1.23.0
    # Additional NeMo dependencies
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0
    - pytorch-lightning>=2.0.0
    # Optimization libraries
    - onnx>=1.14.0
    - onnxruntime-gpu>=1.16.0
    
# Platform-specific notes:
# - For RTX 5090: May need pytorch nightly builds
# - For older GPUs: Adjust pytorch-cuda version as needed
# - For CPU-only: Remove pytorch-cuda and cudatoolkit dependencies